services:
  db:
    image: postgres:17
    container_name: ledger_db
    restart: unless-stopped
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    volumes:
      - ledger_db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}

volumes:
  ledger_db_data:
    driver: local
