// If npx -p @dbml/cli dbml2sql dbml/main.dml -o migrations/new_migration/up.sql fails use the playground
// https://dbml.dbdiagram.io/playground/

Enum "account_type" {
  "asset"
  "liability"
  "equity"
  "revenue"
  "expense"
}

Enum "transfer_status" {
  "pending"
  "cancelled"
  "completed"
}

Table "accounts" {
  "id" SERIAL [pk, increment]
  "account_type" account_type [not null]
  "name" varchar [not null]
  "active" bool [not null, default: false]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp
}

Table "movements" {
  id SERIAL [pk, increment]
  tx integer [not null, ref: > transactions.id]
  account integer [not null, ref: - accounts.id]
  debit integer [not null, default: 0]
  credit integer [not null, default: 0]
  "created_at" timestamp [not null, default: `now()`]

  checks {
    `debit >= 0 AND credit >= 0 AND (debit > 0) != (credit > 0)` [name: 'movements_valid_leg']
  }
}

Table "transactions" {
  "id" SERIAL [pk, increment]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp
}

Table balances {
  account_id integer [pk, ref: - accounts.id]
  balance integer [not null, default: 0]
  blocked integer [not null, default: 0]
  "updated_at" timestamp [not null, default: `now()`]
}

// Temporary table to hold blocked amounts on an account.
// Record should be removed when the amount is unblocked
Table account_blocks {
  id SERIAL [pk, increment]
  account_id integer [not null, ref: - accounts.id]
  amount integer [not null]
  created_at timestamp [not null, default: `now()`]
  transfer_id integer [not null, ref: - transfer_internal.id]
}

Table transfer_internal {
  id SERIAL [pk, increment]
  transaction_id integer [ref: - transactions.id]
  from_account_id integer [not null, ref: - accounts.id]
  to_account_id integer [not null, ref: - accounts.id]
  amount integer [not null]
  initiated_at timestamp [not null, default: `now()`]
  completed_at timestamp
  status transfer_status [not null]
}