// If npx -p @dbml/cli dbml2sql dbml/main.dml --postgres -o migrations/new_migration/up.sql fails use the playground
// https://dbml.dbdiagram.io/playground/

Enum "account_type" {
  "asset"
  "liability"
  "equity"
  "revenue"
  "expense"
}

Enum "transfer_status" {
  "pending"
  "cancelled"
  "completed"
}

Table "accounts" {
  "id" SERIAL [pk, increment]
  "account_type" account_type [not null]
  "name" varchar [not null]
  "active" bool [not null, default: false]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp
}

Table "movements" {
  id SERIAL [pk, increment]
  tx integer [not null, ref: > transactions.id]
  account integer [not null, ref: - accounts.id]
  debit integer [not null, default: 0]
  credit integer [not null, default: 0]
  "created_at" timestamp [not null, default: `now()`]

  checks {
    `debit >= 0 AND credit >= 0 AND (debit > 0) != (credit > 0)` [name: 'movements_valid_leg']
  }
}

Table "transactions" {
  "id" SERIAL [pk, increment]
  "created_at" timestamp [not null, default: `now()`]
  "updated_at" timestamp
}

Table balances {
  account_id integer [pk, ref: - accounts.id]
  balance integer [not null, default: 0]
  "updated_at" timestamp [not null, default: `now()`]
  // last transaction which updated the balance..serves idempotency?
  // we only really need it if balance is not updated atomically with transaction entry.
  // We can add a check to ensure the transaction has at least on debit or credit affecting this account,
  // and maybe that the transaction.created_at > last updated_at of the balance.
  // last_transaction integer [ref: - transactions.id]
}

// Temporary table to hold blocked amounts on an account.
// Record should be removed when the amount is unblocked
Table account_blocks {
  id SERIAL [pk, increment]
  account_id integer [not null, ref: - accounts.id]
  amount integer [not null]
  created_at timestamp [not null, default: `now()`]
  // serves as an idempotency key.. but in that case we shouldn't delete the block record, so
  // instead we add a check to ensure adding a block for a transfer id is only allowed
  // if the transfer is pending. We should also make the field UNIQUE?
  // what if the block is for another reason, should we have a multiple references
  // with "OneOf" semantics.. or just a single reference to a global event id?
  transfer_id integer [not null, unique, ref: - transfer_internal.id]
}

Table transfer_internal {
  id SERIAL [pk, increment]
  // transaction which was recorded when transfer was successfully completed
  transaction_id integer [ref: - transactions.id]
  from_account_id integer [not null, ref: - accounts.id]
  to_account_id integer [not null, ref: - accounts.id]
  amount integer [not null]
  created_at timestamp [not null, default: `now()`]
  completed_at timestamp
  status transfer_status [not null]
}